"""Rigorous unit tests for the Zero-Trust Counterparty Proof Pack Verifier.

Verifies that:
1. Valid proof packs generated by MerkleCheckpointer return verified = True.
2. Forged proof packs missing core fields or with bogus digests return verified = False.
3. Tampered readings or block hashes return verified = False.
4. Tampered Merkle roots return verified = False.
"""

import pytest
import hashlib
from fastapi.testclient import TestClient
from api.main import app
from etp.checkpointer import MerkleCheckpointer, canonical_merkle_root
from etp.meter import compute_canonical_hash

client = TestClient(app)


def test_verifier_accepts_valid_checkpointer_proof():
    """Valid proof pack with 42 readings generated by MerkleCheckpointer must return verified = True."""
    checkpointer = MerkleCheckpointer(storage_path="backend/data/test_checkpoints_rigor.json")
    
    # Generate 42 valid telemetry readings
    readings = []
    mpan = "MPAN-1200098765432"
    first_nonce = 1000
    for i in range(42):
        nonce = first_nonce + i
        reading_kwh = 10.0 + (i * 0.5)
        timestamp = f"2026-09-22T{(i//2):02d}:{(i%2)*30:02d}:00.000Z"
        prev_hash = "0000000000000000000000000000000000000000000000000000000000000000" if i == 0 else readings[-1]["etp_block_hash"]
        
        block_hash = compute_canonical_hash(
            mpan=mpan,
            reading_kwh=reading_kwh,
            timestamp=timestamp,
            prev_hash=prev_hash,
            nonce=nonce,
            crypto_suite_id="ECDSA-P256-SHA256-v1",
            key_id="k-test"
        )
        readings.append({
            "mpan": mpan,
            "reading_kwh": reading_kwh,
            "timestamp": timestamp,
            "prev_hash": prev_hash,
            "etp_nonce": nonce,
            "crypto_suite_id": "ECDSA-P256-SHA256-v1",
            "key_id": "k-test",
            "etp_block_hash": block_hash
        })
        
    ckpt = checkpointer.build_meter_day_checkpoint(
        mpan=mpan,
        day="2026-09-22",
        readings=readings,
        prev_day_last_nonce=999,
        expected_daily_readings=48
    )

    proof_pack = {
        "merkle_root": ckpt["merkle_root"],
        "anchor_digest": ckpt["anchor_digest"],
        "readings": readings,
        "first_nonce": ckpt["first_nonce"],
        "last_nonce": ckpt["last_nonce"],
        "prev_day_last_nonce": ckpt["prev_day_last_nonce"],
        "eod_gap": ckpt["eod_gap"],
        "gap_count": ckpt["gap_count"],
        "expected_readings": 48,
        "observed_leaf_count": ckpt["leaf_count"]
    }

    resp = client.post("/v1/etp/proof-pack/verify", json={"proof_pack": proof_pack})
    assert resp.status_code == 200
    data = resp.json()
    assert data["verified"] is True
    assert data["status"] == "ANCHORED_WITH_GAPS"
    assert data["sequence_gap_count"] == 6


def test_verifier_rejects_forged_matching_strings():
    """Forged proof pack where caller sets merkle_root = anchor_digest = 'bogus' must return verified = False."""
    proof_pack = {
        "merkle_root": "bogus_root_1234567890abcdef",
        "anchor_digest": "bogus_root_1234567890abcdef",
        "expected_readings": 48
    }

    resp = client.post("/v1/etp/proof-pack/verify", json={"proof_pack": proof_pack})
    assert resp.status_code == 200
    data = resp.json()
    assert data["verified"] is False
    assert data["status"] == "FAILED"
    assert data["reason"] == "MISSING_CRYPTOGRAPHIC_FIELDS"


def test_verifier_rejects_tampered_reading_value():
    """Proof pack with one tampered reading kWh value must return verified = False."""
    readings = []
    mpan = "MPAN-1200098765432"
    first_nonce = 1000
    for i in range(48):
        nonce = first_nonce + i
        reading_kwh = 12.0
        timestamp = f"2026-09-22T{(i//2):02d}:{(i%2)*30:02d}:00.000Z"
        prev_hash = "0" * 64 if i == 0 else readings[-1]["etp_block_hash"]
        
        block_hash = compute_canonical_hash(
            mpan=mpan, reading_kwh=reading_kwh, timestamp=timestamp,
            prev_hash=prev_hash, nonce=nonce, crypto_suite_id="ECDSA-P256-SHA256-v1", key_id="k-test"
        )
        readings.append({
            "mpan": mpan, "reading_kwh": reading_kwh, "timestamp": timestamp,
            "prev_hash": prev_hash, "etp_nonce": nonce, "crypto_suite_id": "ECDSA-P256-SHA256-v1",
            "key_id": "k-test", "etp_block_hash": block_hash
        })

    leaf_hashes = [r["etp_block_hash"] for r in readings]
    merkle_root = canonical_merkle_root(leaf_hashes)
    anchor_digest = hashlib.sha256(f"{merkle_root}|1000|1047|48|None|0".encode('utf-8')).hexdigest()

    # Tamper with reading #10 (change kWh from 12.0 to 1.0 without updating block_hash)
    readings[10]["reading_kwh"] = 1.0

    proof_pack = {
        "merkle_root": merkle_root,
        "anchor_digest": anchor_digest,
        "readings": readings,
        "first_nonce": 1000,
        "last_nonce": 1047,
        "prev_day_last_nonce": None,
        "eod_gap": 0,
        "expected_readings": 48
    }

    resp = client.post("/v1/etp/proof-pack/verify", json={"proof_pack": proof_pack})
    assert resp.status_code == 200
    data = resp.json()
    assert data["verified"] is False
    assert data["status"] == "FAILED"
    assert data["reason"] == "BLOCK_HASH_MISMATCH"


def test_verifier_rejects_tampered_merkle_root():
    """Proof pack with a modified Merkle root must return verified = False."""
    readings = []
    mpan = "MPAN-1200098765432"
    first_nonce = 1000
    for i in range(48):
        nonce = first_nonce + i
        reading_kwh = 12.0
        timestamp = f"2026-09-22T{(i//2):02d}:{(i%2)*30:02d}:00.000Z"
        prev_hash = "0" * 64 if i == 0 else readings[-1]["etp_block_hash"]
        
        block_hash = compute_canonical_hash(
            mpan=mpan, reading_kwh=reading_kwh, timestamp=timestamp,
            prev_hash=prev_hash, nonce=nonce, crypto_suite_id="ECDSA-P256-SHA256-v1", key_id="k-test"
        )
        readings.append({
            "mpan": mpan, "reading_kwh": reading_kwh, "timestamp": timestamp,
            "prev_hash": prev_hash, "etp_nonce": nonce, "crypto_suite_id": "ECDSA-P256-SHA256-v1",
            "key_id": "k-test", "etp_block_hash": block_hash
        })

    leaf_hashes = [r["etp_block_hash"] for r in readings]
    real_merkle_root = canonical_merkle_root(leaf_hashes)
    anchor_digest = hashlib.sha256(f"{real_merkle_root}|1000|1047|48|None|0".encode('utf-8')).hexdigest()

    proof_pack = {
        "merkle_root": "a" * 64,  # Forged Merkle root
        "anchor_digest": anchor_digest,
        "readings": readings,
        "first_nonce": 1000,
        "last_nonce": 1047,
        "prev_day_last_nonce": None,
        "eod_gap": 0,
        "expected_readings": 48
    }

    resp = client.post("/v1/etp/proof-pack/verify", json={"proof_pack": proof_pack})
    assert resp.status_code == 200
    data = resp.json()
    assert data["verified"] is False
    assert data["status"] == "FAILED"
    assert data["reason"] == "MERKLE_ROOT_MISMATCH"


def test_verifier_ignores_spoofed_gap_count_and_computes_from_nonces():
    """Fake pack claiming gap_count = 0 must be overridden by true nonce calculation (6 gaps)."""
    checkpointer = MerkleCheckpointer(storage_path="backend/data/test_checkpoints_spoof.json")
    readings = []
    mpan = "MPAN-1200098765432"
    first_nonce = 1000
    for i in range(42):
        nonce = first_nonce + i
        reading_kwh = 10.0
        timestamp = f"2026-09-22T{(i//2):02d}:{(i%2)*30:02d}:00.000Z"
        prev_hash = "0" * 64 if i == 0 else readings[-1]["etp_block_hash"]
        
        block_hash = compute_canonical_hash(
            mpan=mpan, reading_kwh=reading_kwh, timestamp=timestamp,
            prev_hash=prev_hash, nonce=nonce, crypto_suite_id="ECDSA-P256-SHA256-v1", key_id="k-test"
        )
        readings.append({
            "mpan": mpan, "reading_kwh": reading_kwh, "timestamp": timestamp,
            "prev_hash": prev_hash, "etp_nonce": nonce, "crypto_suite_id": "ECDSA-P256-SHA256-v1",
            "key_id": "k-test", "etp_block_hash": block_hash
        })

    ckpt = checkpointer.build_meter_day_checkpoint(
        mpan=mpan, day="2026-09-22", readings=readings, prev_day_last_nonce=999, expected_daily_readings=48
    )

    proof_pack = {
        "merkle_root": ckpt["merkle_root"],
        "anchor_digest": ckpt["anchor_digest"],
        "readings": readings,
        "first_nonce": ckpt["first_nonce"],
        "last_nonce": ckpt["last_nonce"],
        "prev_day_last_nonce": ckpt["prev_day_last_nonce"],
        "eod_gap": ckpt["eod_gap"],
        "gap_count": 0,  # Spoofed gap count claiming 0 gaps!
        "expected_readings": 48,
        "observed_leaf_count": ckpt["leaf_count"]
    }

    resp = client.post("/v1/etp/proof-pack/verify", json={"proof_pack": proof_pack})
    assert resp.status_code == 200
    data = resp.json()
    assert data["verified"] is True
    assert data["status"] == "ANCHORED_WITH_GAPS"
    assert data["sequence_gap_count"] == 6  # Derived from nonces, ignoring pack's gap_count: 0

