# Copyright (c) 2026 Meldra AI Ltd. All rights reserved.
"""
tests/test_golden_vectors.py

Dynamically loads backend/tests/golden_vectors.json generated by tools/gen_golden_vectors.py.
Asserts authoritative Python outputs against golden JSON test vectors to guarantee zero spec drift.
"""

from __future__ import annotations

import sys
import json
from pathlib import Path

root_dir = Path(__file__).resolve().parent.parent.parent
backend_dir = Path(__file__).resolve().parent.parent
if str(root_dir) not in sys.path:
    sys.path.insert(0, str(root_dir))
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

import pytest
from backend.etp.meter import compute_canonical_hash
from backend.etp.route_mutator import RouteMutator
from backend.etp.checkpointer import canonical_merkle_root


@pytest.fixture
def golden_data():
    json_path = backend_dir / "tests" / "golden_vectors.json"
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def test_golden_canonical_hash_vector(golden_data):
    """Validates exact SHA-256 canonical hash vector against golden JSON output."""
    inputs = golden_data["inputs"]
    expected = golden_data["expected_outputs"]["canonical_hash"]

    hash_val = compute_canonical_hash(
        mpan=inputs["mpan"],
        reading_kwh=inputs["reading_kwh"],
        timestamp=inputs["timestamp"],
        prev_hash=inputs["prev_hash"],
        nonce=inputs["nonce"],
        crypto_suite_id=inputs["crypto_suite_id"],
        key_id=inputs["key_id"]
    )
    assert len(hash_val) == 64
    assert hash_val == expected, f"Canonical hash mismatch: got {hash_val}, expected {expected}"


def test_golden_route_mutator_scramble_vector(golden_data):
    """Validates exact HMAC-SHA256 12-char hex route scramble against golden JSON output."""
    inputs = golden_data["inputs"]
    expected = golden_data["expected_outputs"]["route_scramble"]

    secret_key = bytes.fromhex(inputs["secret_key_hex"])
    mutator = RouteMutator(secret_key=secret_key, window_s=60)
    scramble = mutator._scramble_hex(inputs["window"])
    assert len(scramble) == 12
    assert scramble == expected, f"Route scramble mismatch: got {scramble}, expected {expected}"


def test_golden_merkle_tree_domain_separation_vector(golden_data):
    """Validates domain-separated Merkle tree root vector against golden JSON output."""
    inputs = golden_data["inputs"]
    leaves = inputs["test_leaves"]

    root = canonical_merkle_root(leaves)
    assert len(root) == 64
